In [1]:
# 기본
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# KFold (교차 검증을 사용하기 위해)
from sklearn.model_selection import KFold
from sklearn.model_selection import StratifiedKFold

# 교차검증 함수
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import cross_validate

# 학습 데이터와 검증 데이터로 나누는 함수
from sklearn.model_selection import train_test_split

# 데이터 전처리
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

# 하이퍼 파라미터 튜닝
from sklearn.model_selection import GridSearchCV

# 평가 함수
from sklearn.metrics import accuracy_score

# 머신러닝 알고리즘 - 분류
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier

# 머신러닝 알고리즘 - 회귀
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import ElasticNet
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import  XGBRegressor

# 머신러닝 알고리즘 - 군집
from sklearn.cluster import KMeans
from sklearn.cluster import MeanShift

# 머신러닝 알고리즘 - 차원축소
from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

# 딥러닝 알고리즘 
from keras.models import Sequential
from keras.layers import Dense
import tensorflow as tf

# 저장
import pickle

# 그래프 설정
# plt.rcParams['font.family'] = 'Malgun Gothic'   # 윈도우용
plt.rcParams['font.family'] = 'AppleGothic'   # 맥용
plt.rcParams['font.size'] = 16                  # 폰트 크기
plt.rcParams['figure.figsize'] = 10,8          # 그래프 크기
plt.rcParams['axes.unicode_minus'] = False     # - 기호 깨짐 방지


# 경고 메시지가 안나오게 하기
import warnings
warnings.filterwarnings('ignore')

### 데이터 가져오기

In [2]:
# 준비된 수술 환자 데이터를 가져온다.
# 1이 생존, 0이 사망
df1 = pd.read_csv('../dataset/ThoraricSurgery.csv')
df1.head()

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0    1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1    8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2   14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   
3   17  2  2.21  1.88  0    0    1    0    0    0  12    0    0    0    1   
4   18  2  2.96  1.67  0    0    0    0    0    0  12    0    0    0    1   

   0.9  62  0.10  
0    0  60     0  
1    0  66     1  
2    0  80     1  
3    0  56     0  
4    0  61     0

### 입력과 결과 데이터 나누기

In [3]:
x = df1.drop('0.10', axis=1)
y = df1['0.10']
display(x)
display(y)

293  1   3.8   2.8  0  0.1  0.2  0.3  0.4  0.5  12  0.6  0.7  0.8  1.1  \
0      1  2  2.88  2.16  1    0    0    0    1    1  14    0    0    0    1   
1      8  2  3.19  2.50  1    0    0    0    1    0  11    0    0    1    1   
2     14  2  3.98  3.06  2    0    0    0    1    1  14    0    0    0    1   
3     17  2  2.21  1.88  0    0    1    0    0    0  12    0    0    0    1   
4     18  2  2.96  1.67  0    0    0    0    0    0  12    0    0    0    1   
..   ... ..   ...   ... ..  ...  ...  ...  ...  ...  ..  ...  ...  ...  ...   
464   98  6  3.04  2.40  2    0    0    0    1    0  11    0    0    0    1   
465  369  6  3.88  2.72  1    0    0    0    1    0  12    0    0    0    1   
466  406  6  5.36  3.96  1    0    0    0    1    0  12    0    0    0    0   
467   25  8  4.32  3.20  0    0    0    0    0    0  11    0    0    0    0   
468  447  8  5.20  4.10  0    0    0    0    0    0  12    0    0    0    0   

     0.9  62  
0      0  60  
1      0  66  
2      0  80  
3      0  56  
4      0  61  
..   ...  ..  
464    0  76  
465    0  77  
466    0  62  
467    0  58  
468    0  49  

[469 rows x 17 columns]

0      0
1      1
2      1
3      0
4      0
      ..
464    0
465    0
466    0
467    1
468    0
Name: 0.10, Length: 469, dtype: int64

### 학습데이터와 검증데이터 나누기

In [4]:
train_x, test_x, train_y, test_y = train_test_split(x,y)

### 머신러닝

In [5]:
model1 = LogisticRegression()
model1.fit(train_x, train_y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [6]:
# 평가
pred1 = model1.predict(test_x)
pred1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# 스코어 확인
r1 = accuracy_score(test_y, pred1)
r1

0.864406779661017

### 딥러닝

In [8]:
# 구조 결정
model2 = Sequential()
model2.add(Dense(30, input_dim = 17, activation='relu'))
model2.add(Dense(1, activation='sigmoid'))

In [9]:
# 실행
model2.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model2.fit(train_x, train_y, epochs = 30, batch_size=10)

Epoch 1/30
36/36 [==============================] - 0s 661us/step - loss: 0.1679 - accuracy: 0.8320
Epoch 2/30
36/36 [==============================] - 0s 656us/step - loss: 0.1710 - accuracy: 0.8282
Epoch 3/30
36/36 [==============================] - 0s 630us/step - loss: 0.1539 - accuracy: 0.8458
Epoch 4/30
36/36 [==============================] - 0s 605us/step - loss: 0.1407 - accuracy: 0.8586
Epoch 5/30
36/36 [==============================] - 0s 633us/step - loss: 0.1626 - accuracy: 0.8349
Epoch 6/30
36/36 [==============================] - 0s 582us/step - loss: 0.1263 - accuracy: 0.8684
Epoch 7/30
36/36 [==============================] - 0s 632us/step - loss: 0.1549 - accuracy: 0.8413
Epoch 8/30
36/36 [==============================] - 0s 613us/step - loss: 0.1268 - accuracy: 0.8610
Epoch 9/30
36/36 [==============================] - 0s 639us/step - loss: 0.1641 - accuracy: 0.8359
Epoch 10/30
36/36 [==============================] - 0s 636us/step - loss: 0.1222 - accuracy: 0.8778

In [10]:
# 예측결과 (예측 결과값이 1일 확률)
pred2 = model2.predict(test_x)
pred2

array([[2.14222074e-03],
       [1.21134151e-04],
       [1.06053054e-01],
       [2.00016826e-01],
       [1.21646225e-02],
       [2.44975090e-04],
       [2.98630953e-01],
       [5.10632992e-04],
       [1.05490417e-05],
       [1.40816063e-01],
       [4.67265927e-05],
       [1.60109699e-02],
       [4.18432057e-02],
       [6.63846731e-04],
       [5.16614318e-03],
       [2.07866833e-06],
       [1.38521194e-04],
       [8.05705786e-04],
       [4.16499376e-03],
       [1.01203412e-01],
       [3.96088660e-02],
       [1.06787682e-03],
       [3.63662839e-03],
       [1.34968758e-03],
       [1.01238504e-04],
       [3.99470329e-04],
       [1.32754445e-03],
       [2.55321562e-02],
       [1.08032536e-05],
       [4.36395407e-04],
       [6.18451713e-06],
       [2.72750854e-04],
       [1.41538799e-01],
       [1.26150250e-03],
       [2.83250809e-02],
       [7.15425267e-05],
       [2.04536319e-03],
       [5.67758381e-02],
       [1.23536289e-02],
       [9.28759575e-04],


In [11]:
# 예측결과 확인 
result2 = (pred2 >= 0.5).astype(int)
result2

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [12]:
r2 = accuracy_score(test_y, result2)
r2

0.864406779661017