In [1]:
import numpy as np

In [20]:
# 기울기 a와 y절편 b
a = 2.3
b = 79

In [21]:
# 입력과 결과
x = [2,4,6,8]
y = [81, 93, 91, 97]

In [22]:
# 입력된 값에 따라 결과를 예측하는 함수
def predict(x):
    return a * x + b

In [23]:
# 예측 결과를 추출한다.
# 예측 결과를 담을 리스트
pred_list = []

for v1 in x:
    a1 = predict(v1)
    pred_list.append(a1)
pred_list

[83.6, 88.2, 92.8, 97.4]

In [24]:
# 계산을 쉽게 하기 위해 ndarray를 생성한다.
array1 = np.array(pred_list)
array2 = np.array(y)

print(array1)
print(array2)

[83.6 88.2 92.8 97.4]
[81 93 91 97]


In [25]:
# 진짜 결과와 예측 결과를 뺀 값을 가져온다.
array3 = array1 - array2
print(array3)

[ 2.6 -4.8  1.8  0.4]


In [26]:
# 제곱을 구한다.
array4 = array3 ** 2
print(array4)

[ 6.76 23.04  3.24  0.16]


In [27]:
# 평균을 구한다.
mse = array4.mean()
print(f'평균 제곱오차값 : {mse}')

평균 제곱오차값 : 8.299999999999985
